#!/bin/sh

RBENV_ROOT=~/.rbenv

git clone https://github.com/sstephenson/rbenv.git ${RBENV_ROOT}
git clone https://github.com/sstephenson/ruby-build.git ${RBENV_ROOT}/plugins/ruby-build
git clone https://github.com/sstephenson/rbenv-vars.git ${RBENV_ROOT}/plugins/rbenv-vars
git clone https://github.com/sstephenson/rbenv-gem-rehash.git ${RBENV_ROOT}/plugins/rbenv-gem-rehash
git clone https://github.com/sstephenson/rbenv-default-gems.git ${RBENV_ROOT}/plugins/rbenv-default-gems
