set nocompatible
filetype off

" =====================================
" Plugins
" =====================================
set runtimepath+=~/.vim/bundle/vundle
call vundle#rc()
Plugin 'gmarik/vundle'

Plugin 'taglist.vim'
Plugin 'ctrlp.vim'
Plugin 'yaifa.vim'
Plugin 'rizzatti/funcoo.vim'
Plugin 'rizzatti/dash.vim'

" Syntax
Plugin 'fatih/vim-go'
Plugin 'kchmck/vim-coffee-script'
Plugin 'leafgarland/typescript-vim'

" Themes
Plugin 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}
Plugin 'github-theme'

" =====================================
" Syntax and file types
" =====================================
set encoding=utf-8
syntax enable
filetype on
filetype plugin on
filetype indent on

" Whitespace
" set nowrap
set tabstop=8
set shiftwidth=8
set softtabstop=8
set listchars=tab:\ \ ,trail:·
set nolist
set expandtab
set smarttab
set smartindent
set autoindent
set backspace=start,eol,indent whichwrap+=<,>,[,]

set number
set cursorline
set modeline

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

set scs
set showtabline=1
set ruler

" netrw

"let g:netrw_hide=1
let g:netrw_liststyle=3
let g:netrw_list_hide='.git,.DS_Store'
"let g:netrw_preview=1
"let g:netrw_winsize=30

" Turn off blinking cursor
set guicursor+=n:blinkon0

set foldenable
set foldmethod=syntax
set foldlevel=10

" Use system clipboard
" set clipboard=unnamed

autocmd FileType javascript setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
autocmd FileType ruby       setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType rdoc       setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType go         setlocal tabstop=8 shiftwidth=8 softtabstop=8 noexpandtab
autocmd FileType eruby      setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType haml       setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType sass       setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType cucumber   setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType python     setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab textwidth=79 cinwords=if,elif,else,for,while,with,try,except,finally,def,class
autocmd FileType make       setlocal noexpandtab
autocmd FileType markdown   setlocal wrap wrapmargin=2 textwidth=72|map <buffer> <Leader>p :Hammer<CR>

autocmd BufNewFile,BufRead     *.json set ft=javascript
autocmd BufNewFile,BufReadPost *.coffee setl foldmethod=indent
autocmd BufNewFile,BufReadPost *.coffee setl shiftwidth=2 expandtab

" autocmd FileType go autocmd BufWritePre <buffer> Fmt
autocmd FileType go compiler go

" vim-go
let g:go_fmt_command = "goimports"
let g:go_highlight_methods = 1
let g:go_highlight_structs = 0

" Don't create extra files
"set nobackup
"set nowritebackup
"set noswapfile

" Status line
set laststatus=2
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set titlestring=%t%(\ -\ %{expand(\"%:~:.:h\")}%)%(\ [%n]%)%(\ %M%)%(\ %a%)

if has("unix")
  " Invisible character symbols (match textmate)
  set listchars=tab:▸\ ,eol:¬
endif

" Mappings
let mapleader = "\\"

:nmap <silent> <leader>d <Plug>DashSearch

" Color scheme
colorscheme github
set background=dark

" MacVIM shift+arrow keys behavior
if has("gui_macvim")
  let macvim_hig_shift_movement = 1
endif

" % to bound from do to end
runtime! macros/matchit.vim

