set nocompatible
filetype off

" =====================================
" Plugins
" =====================================
set runtimepath+=~/.vim/bundle/vundle
call vundle#rc()
Plugin 'gmarik/vundle'

Plugin 'taglist.vim'
Plugin 'ctrlp.vim'
Plugin 'yaifa.vim'
Plugin 'rizzatti/funcoo.vim'
Plugin 'rizzatti/dash.vim'

" Syntax
Plugin 'jnwhiteh/vim-golang'
Plugin 'kchmck/vim-coffee-script'
Plugin 'leafgarland/typescript-vim'

" Themes
Plugin 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}

" =====================================
" Syntax and file types
" =====================================
set encoding=utf-8
syntax enable
filetype on
filetype plugin on
filetype indent on

" Whitespace
" set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set listchars=tab:\ \ ,trail:·
set nolist
set expandtab
set smarttab
set smartindent
set autoindent
set backspace=start,eol,indent whichwrap+=<,>,[,]

set number
set cursorline
set modeline

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

set scs
set showtabline=1
set ruler

" netrw

"let g:netrw_hide=1
let g:netrw_liststyle=3
let g:netrw_list_hide='.git,.DS_Store'
"let g:netrw_preview=1
"let g:netrw_winsize=30

" Turn off blinking cursor
set guicursor+=n:blinkon0

set foldenable
set foldmethod=syntax
set foldlevel=10

" Use system clipboard
" set clipboard=unnamed

autocmd FileType javascript set tabstop=4 shiftwidth=4 softtabstop=4 expandtab
autocmd FileType ruby       set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType rdoc       set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType eruby      set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType haml       set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType sass       set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType cucumber   set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType python     set tabstop=4 shiftwidth=4 softtabstop=4 expandtab textwidth=79 cinwords=if,elif,else,for,while,with,try,except,finally,def,class
autocmd FileType make       set noexpandtab
autocmd FileType markdown   set wrap wrapmargin=2 textwidth=72|map <buffer> <Leader>p :Hammer<CR>
autocmd BufNewFile,BufRead *.json set ft=javascript
autocmd FileType go compiler go

autocmd BufNewFile,BufReadPost *.coffee setl foldmethod=indent
autocmd BufNewFile,BufReadPost *.coffee setl shiftwidth=2 expandtab

" Don't create extra files
"set nobackup
"set nowritebackup
"set noswapfile

" Status line
set laststatus=2
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set titlestring=%t%(\ -\ %{expand(\"%:~:.:h\")}%)%(\ [%n]%)%(\ %M%)%(\ %a%)

if has("unix")
  " Invisible character symbols (match textmate)
  set listchars=tab:▸\ ,eol:¬
endif

" Mappings
let mapleader = "\\"

:nmap <silent> <leader>d <Plug>DashSearch

" Color scheme
colorscheme github
set background=light

" MacVIM shift+arrow keys behavior
if has("gui_macvim")
  let macvim_hig_shift_movement = 1
endif

" % to bound from do to end
runtime! macros/matchit.vim

