#  -*- mode: unix-shell-script; -*-

# ========================================
# Per-machine extras
# ========================================
if [ -e ~/.zsh_local/zshenv ]; then
	. ~/.zsh_local/zshenv
fi
